### ISSUE TITLE
One-hot vs Embedding?

### ISSUE THREAD

**Issue by naisanza** [unixpickle/learning-tf#2]
I noticed in your char-based rnn, you've created a one-hot encoded array (if I'm correct). From a separate conversation, an embedding layer was explained to be [preferable over one-hot encoding](https://github.com/fchollet/keras/issues/4838#issuecomment-326688772)

I'm wondering what your take on it is?

https://github.com/unixpickle/learning-tf/blob/master/char_rnn.py#L141

**Comment by unixpickle** [comment]
When people talk about embedding layers, they are really just talking about sparse matrices. Sparse matrices are just an optimization for a specific kind of data. As this was a learning project, I didn't care about performance too much; I just wanted things to be [simple](https://github.com/unixpickle/learning-tf/blob/master/char_rnn.py#L64-L66). Using sparse computation would probably have been premature optimization.

Also, since I specifically wanted to learn the basics of TF, I didn't want to use any helpers like Keras (which is where the "embedding layer" comes from).

**Comment by naisanza** [comment]
@unixpickle Could one-hot encoding be seen as basic "lego blocks" where it can be used to train any data on any model (from zero optimization and let the model find its own optimization)? And sparse matrices are like "ikea furniture" where they're meant for one or two types of data and models (essentially a specific handful of use cases)?

**Comment by unixpickle** [comment]
This is more of a computing problem than a machine learning problem. Using sparse matrices is a code optimization; it doesn't actually affect what the model is doing or how it learns. If you don't use sparse matrices, the same matrix-matrix multiplications will take place, they will just be slower and use more memory.

In this case, there's no way for the model to "find its own optimization". Most neural networks have no way of affecting their execution time. No matter what they learn, they do the same kinds of matrix multiplications or convolutions the whole way through.

**Comment by naisanza** [comment]
@unixpickle I suppose I thought when you said premature optimizations, I thought you meant optimizations in the neural network (like "optimizing" the weights during back propagation). But I see it actually meant code optimization.

I'm learning all of this backwards, instead of traditionally understanding the math first. I've kind of just jumped in, and tried to understand things backwards, taking an example model and peeling back what the programming arguments do, until I figure out why it's used and why it works. It's a lot of head butting; learning by brute forcing concepts until they all fall into place. Like how an LSTM input shape [is referred to in twelve different ways](https://github.com/TheShellLand/tenderflow/blob/master/keras/lstm_101.py#L345).

The biggest initial challenge I'm trying to figure out is how to determine the output shapes of a layer. One person related it to alchemy.
